version: '3'

services:
  redis:
    image: redis:alpine 
    container_name: go-redis
    restart: always
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "$REDIS_PORT:6379"
    networks:
      - go-redis

networks:
  go-redis:
    driver: bridge
